// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHv40B-Qd0odbi5zjFinPvZcuuudtKbqM',
    appId: '1:879162661917:web:2e3cace7d0652f40b5baf4',
    messagingSenderId: '879162661917',
    projectId: 'pathly-firebase',
    authDomain: 'pathly-firebase.firebaseapp.com',
    storageBucket: 'pathly-firebase.firebasestorage.app',
    measurementId: 'G-QV395G6EDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY1bF_z5djz5UYMyHwvIjyQHQ4QCL5qxs',
    appId: '1:879162661917:android:d1f89c37006f9e49b5baf4',
    messagingSenderId: '879162661917',
    projectId: 'pathly-firebase',
    storageBucket: 'pathly-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJqeFyofwp4xV1v3KWT1PKgyWuw-1h19M',
    appId: '1:879162661917:ios:c330e7f4d9e3d251b5baf4',
    messagingSenderId: '879162661917',
    projectId: 'pathly-firebase',
    storageBucket: 'pathly-firebase.firebasestorage.app',
    iosBundleId: 'com.example.pathly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJqeFyofwp4xV1v3KWT1PKgyWuw-1h19M',
    appId: '1:879162661917:ios:c330e7f4d9e3d251b5baf4',
    messagingSenderId: '879162661917',
    projectId: 'pathly-firebase',
    storageBucket: 'pathly-firebase.firebasestorage.app',
    iosBundleId: 'com.example.pathly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHv40B-Qd0odbi5zjFinPvZcuuudtKbqM',
    appId: '1:879162661917:web:bf55a1a4da48041fb5baf4',
    messagingSenderId: '879162661917',
    projectId: 'pathly-firebase',
    authDomain: 'pathly-firebase.firebaseapp.com',
    storageBucket: 'pathly-firebase.firebasestorage.app',
    measurementId: 'G-QKLWK90BN2',
  );
}
